logging:
  level: INFO
  loggers:
    com.bitcoin: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

jerseyClient:
  timeout: 1s
  connectionTimeout: 1s

blockchainHostname: https://blockchain.info
